### ISSUE TITLE
Some textures will disappear in sv_pure 1 servers

### ISSUE THREAD

**Issue by FaithFoesntLie** [ModdingTF2/The-closest-thing-to-an-updated-version-of-TF2-TIP#1]
For example, the heavy will just turn completely invisible, and it's overall just a buggy mess.
Please fix.

**Comment by kevinvanrijn** [comment]
I have rebuild the repository from scratch so I actually know what files came from where and everything seems stable so far. (At least on my end.)

So I'm releasing [3.3.6](https://github.com/ModdingTF2/The-closest-thing-to-an-updated-version-of-TF2-TIP/releases) which should no longer break when playing on sv_pure 1 servers. Let me know if this actually works.

**Comment by kevinvanrijn** [comment]
[3.3.7.fix.1](https://github.com/ModdingTF2/The-closest-thing-to-an-updated-version-of-TF2-TIP/releases) should have fixed the last occurence of this happening. Don't hesitate to open a new issue if things are still breaking.
