### ISSUE TITLE
Rocket model invisible

### ISSUE THREAD

**Issue by Aerden** [ModdingTF2/The-closest-thing-to-an-updated-version-of-TF2-TIP#3]
When firing a rocket the rocket model is invisible for the first few frames, this is also the case when reloading the rocket launcher, the rocket is completely invisible on reloading and won't appear
![20180408170839_1](https://user-images.githubusercontent.com/27950824/38465546-ac42e2fa-3b4f-11e8-9a2e-90a66a56c407.jpg)

**Comment by kevinvanrijn** [comment]
Fixed in [3.3.7.fix.2](https://github.com/ModdingTF2/The-closest-thing-to-an-updated-version-of-TF2-TIP/releases)

**Comment by kevinvanrijn** [comment]
I forgot to talk about the rocket being invisible when firing. This happens in unmodded TF2 as well.
