### ISSUE TITLE
Crashing on join server

### ISSUE THREAD

**Issue by Aerden** [ModdingTF2/The-closest-thing-to-an-updated-version-of-TF2-TIP#4]
TF2 crashes everytime I join a valve server with TIP installed

**Comment by kevinvanrijn** [comment]
Well... This isn't the case for me. So I'm going to need some additional information.

I'm assuming there is nothing wrong with your installation but just to make sure, could you [verify the integrity of your game cache](https://www.youtube.com/watch?v=4PZng5vj9ic) and try to join a server afterwards?

---

And then for finding the actual cause of your crashes:

* Please take a picture of your Main Menu.
* What does the rest of your [custom folder](https://www.youtube.com/embed/CWlSLH-8pXM?autoplay=1&start=2&end=20) look like? (TF2 tends to crash when conflicting mods override certain files.)
* Have you set any [launch options](https://www.youtube.com/watch?v=ixJrwGGLSN0)?
* In the [cfg folder](https://www.youtube.com/embed/3rOZFxcL_Rs?autoplay=1&start=18&end=27), what are the contents of  `autoexec.cfg` and `config.cfg`?

**Comment by Aerden** [comment]
Verifying the integrity seems to have fixed it. Thanks
