### ISSUE TITLE
Small Texture Bug

### ISSUE THREAD

**Issue by FireWolf700** [ModdingTF2/The-closest-thing-to-an-updated-version-of-TF2-TIP#8]
![20180823022802_1](https://user-images.githubusercontent.com/38019493/44519444-eb17d600-a681-11e8-9b96-8227e5f4cf86.jpg)

**Comment by FireWolf700** [comment]
Found on the Rockets and Bullets in the Ammo Crate in the Supply Locker

**Comment by kevinvanrijn** [comment]
Right. The locker model requires the updated ammo box. Otherwise this happens.

**Comment by kevinvanrijn** [comment]
This has been fixed in [3.3.11](https://github.com/ModdingTF2/The-closest-thing-to-an-updated-version-of-TF2-TIP/releases)
